# Generated by Django 5.2.13 on 2026-04-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_document_ai_summary_document_chapter_map_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="audio_duration_seconds",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="document",
            name="audio_local_ref",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="source_mime_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="document",
            name="source_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="source_size_bytes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="document",
            name="storage_mode",
            field=models.CharField(default="local_device", max_length=24),
        ),
        migrations.AlterField(
            model_name="document",
            name="source_file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
