# Generated by Django 5.2.13 on 2026-04-21 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_audiojob_extractionjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterNavigationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("seek", "Seek"),
                            ("semantic_seek", "Semantic Seek"),
                            ("playback_seek", "Playback Seek"),
                            ("detect_chapters", "Detect Chapters"),
                        ],
                        max_length=32,
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=255)),
                ("chapter_index", models.IntegerField(blank=True, null=True)),
                ("chapter_title", models.CharField(blank=True, max_length=255)),
                ("position_seconds", models.FloatField(default=0.0)),
                ("confidence", models.FloatField(default=0.0)),
                ("provider", models.CharField(blank=True, max_length=64)),
                ("fallback_used", models.BooleanField(default=False)),
                ("match_excerpt", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation_events",
                        to="api.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_navigation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="api_chapter_user_id_8ab351_idx"
                    ),
                    models.Index(
                        fields=["document", "created_at"], name="api_chapter_documen_3beaf8_idx"
                    ),
                    models.Index(
                        fields=["event_type", "created_at"], name="api_chapter_event_t_259e7a_idx"
                    ),
                ],
            },
        ),
    ]
